"""Add current_members to rooms

Revision ID: b39bccfc1d71
Revises: d17f78a5464b
Create Date: 2026-01-04 14:30:25.759017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39bccfc1d71'
down_revision: Union[str, Sequence[str], None] = 'd17f78a5464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('current_members', sa.Integer(), nullable=True,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'current_members')
    # ### end Alembic commands ###
