"""Add username to room_members

Revision ID: fe63bf09bf5f
Revises: 3d08ec8e957f
Create Date: 2026-01-04 14:20:54.373386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe63bf09bf5f'
down_revision: Union[str, Sequence[str], None] = '3d08ec8e957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.add_column('room_members', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint(op.f('room_members_room_id_fkey'), 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rooms', 'users', ['host_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(op.f('room_members_room_id_fkey'), 'room_members', 'rooms', ['room_id'], ['id'])
    op.drop_column('room_members', 'username')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
